api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
         pagination:
            # Pour activer ou desactiver la pagination.
            enabled: false
            # Pour configurer le nombre d'item par page
            items_per_page: 30
            # Pour permettre à l'utilisateur d'activier ou désactiver la pagination
            client_enabled: true
            # Pour permettre à l'utilisateur de definir le nombre d'élément par page
            client_items_per_page: true
         